module.exports = {
  verbose: true,
  setupFilesAfterEnv: ['<rootDir>/jest.js'],
  roots: ['./'],
  testEnvironment: 'jest-environment-jsdom',
  testEnvironmentOptions: {
    customExportConditions: ['node', 'node-addons'],
  },
  coverageReporters: ['lcov'],
  coverageDirectory: './coverage',
  collectCoverageFrom: [
    'src/**/*.ts',
    'src/**/*.tsx',
    // exclude files from coverage
    '!src/**/index.ts',
    '!src/**/index.tsx',
    '!src/**/App.tsx',
    '!src/**/react-app-env.d.ts',
    '!src/**/reportWebVitals.ts',
    '!src/**/setupTests.ts',
  ],
  moduleFileExtensions: ['js', 'jsx', 'ts', 'tsx'],
  moduleDirectories: ['node_modules'],
  moduleNameMapper: {
    '^@assets/(.*)$': '<rootDir>/src/assets/$1',
    '^@assets$': '<rootDir>/src/assets',
    '^@components/(.*)$': '<rootDir>/src/components/$1',
    '^@components$': '<rootDir>/src/components',
    '^@data/(.*)$': '<rootDir>/src/data/$1',
    '^@data$': '<rootDir>/src/data',
    '^@providers/(.*)$': '<rootDir>/src/providers/$1',
    '^@providers$': '<rootDir>/src/providers',
    '^@localization/(.*)$': '<rootDir>/src/localization/$1',
    '^@localization$': '<rootDir>/src/localization',
    '^@routes/(.*)$': '<rootDir>/src/routes/$1',
    '^@routes$': '<rootDir>/src/routes',
    '^@screens/(.*)$': '<rootDir>/src/screens/$1',
    '^@screens$': '<rootDir>/src/screens',
    '^@uiStore/(.*)$': '<rootDir>/src/store/ui/$1',
    '^@uiStore$': '<rootDir>/src/store/ui',
    '^@appStore/(.*)$': '<rootDir>/src/store/app/$1',
    '^@appStore$': '<rootDir>/src/store/app',
    '^@services/(.*)$': '<rootDir>/src/services/$1',
    '^@services$': '<rootDir>/src/services',
    '^@testUtils/(.*)$': '<rootDir>/src/testUtils/$1',
    '^@testUtils$': '<rootDir>/src/testUtils',
  },
  transform: {
    '^.+.(css|styl|less|sass|scss|png|jpg|ttf|woff|woff2)$':
      'jest-transform-stub',
    '^.+\\.(js|jsx|ts|tsx)$': [
      'ts-jest',
      {
        isolatedModules: true,
        tsconfig: {
          module: 'commonjs',
          moduleResolution: 'node',
        },
      },
    ],
  },
  // coverageThreshold: {
  //   global: {
  //     branches: 80,
  //     functions: 80,
  //     lines: 80,
  //     statements: -10,
  //   },
  // },
};
