name: Deploy job

on:
  release:
    types: [published]

jobs:
  setup_and_deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn build --if-present
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.WOT_FTP_SERVER }}
          username: ${{ secrets.WOT_FTP_ACCOUNT }}
          password: ${{ secrets.WOT_FTP_PASSWORD }}
          local-dir: ./build/
          server-dir: ./
