name: Releases
on:
  pull_request:
    branches:
      - production
    types: [closed]

permissions:
  contents: write

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PA_TOKEN }}
      - name: Enable Corepack
        run: corepack enable
      - name: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'yarn'
      - name: conventional changelog action
        id: changelog
        # https://github.com/TriPSs/conventional-changelog-action
        uses: TriPSs/conventional-changelog-action@latest
        with:
          # you can also create separate token to trace action
          github-token: '${{ secrets.PA_TOKEN }}'
          git-user-name: 'WorldOfTech bot'
          output-file: false
      - name: create release
        # https://github.com/actions/create-release
        uses: softprops/action-gh-release@v1
        if: ${{steps.changelog.outputs.skipped == 'false'}}
        env:
          # This token is provided by Actions, you do not need to create your own token
          GITHUB_TOKEN: ${{ secrets.PA_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          name: ${{ steps.changelog.outputs.tag }}
          body: ${{steps.changelog.outputs.clean_changelog}}
          draft: false
          prerelease: false
